<?
		$hebTranlation = array("created_at"=>"נוצר בתאריך",
							   "name"=>"שם",
							   "save"=>"שמור",
							   "clear"=>"אפס",
							   "location"=>"מיקום",
						       "customer_name"=>"שם לקוח",
						       "serial_num"=>"מספר סידורי",
						       "model"=>"דגם מכונה",
						       "counter"=>"מונה",
						       "address"=>"כתובת",
						       "phone"=>"טלפון",
						       "first_name"=>"שם פרטי",
						       "last_name"=>"שם משפחה",
						       "updated_at"=>"עודכן בתאריך",
						       "problem_description"=>"תיאור תקלה",
						       "contact_person"=>"איש קשר",
						       "phone_number"=>"מס טלפון",
						       "customer_comments"=>"הערות נוספות",
						       "email"=>"דואר אלקטרוני",
						       "pass"=>"סיסמה",
						       "producer"=>"יצרן",
						       "type"=>"סוג מכשיר",
						       "toner_name"=>"סוג טונר",
						       "machine_image"=>"תמונת מכשיר",
						       "groupm"=>"קבוצת מכשירים");

?>